### ISSUE TITLE
Loading tagged images of persons fails

### ISSUE THREAD

**Issue by z38** [php-tmdb/api#146]
When loading a person, the parsing of tagged images fails:
```plain
PHP Fatal error:  Uncaught RuntimeException: Unable to detect the image type. in /app/vendor/php-tmdb/api/lib/Tmdb/Factory/ImageFactory.php:69
Stack trace:
#0 /app/vendor/php-tmdb/api/lib/Tmdb/Factory/AbstractFactory.php(130): Tmdb\Factory\ImageFactory->createMediaImage(Array)
#1 /app/vendor/php-tmdb/api/lib/Tmdb/Factory/PeopleFactory.php(96): Tmdb\Factory\AbstractFactory->createResultCollection(Array, 'createMediaImag...')
#2 /app/vendor/php-tmdb/api/lib/Tmdb/Repository/PeopleRepository.php(55): Tmdb\Factory\PeopleFactory->create(Array)
#3 /app/test.php(9): Tmdb\Repository\PeopleRepository->load('996701')
#4 {main}
  thrown in /app/vendor/php-tmdb/api/lib/Tmdb/Factory/ImageFactory.php on line 69
```

The value passed to `ImageFactory::createMediaImage`:
```php
array (
  'iso_639_1' => NULL,
  'vote_count' => 72,
  'media_type' => 'movie',
  'file_path' => '/lIv1QinFqz4dlp5U4lQ6HaiskOZ.jpg',
  'aspect_ratio' => 0.66666666666666996,
  'media' => 
  array (
    'release_date' => '2014-10-10',
    'vote_count' => 3749,
    'video' => false,
    'adult' => false,
    'vote_average' => 8.3000000000000007,
    'title' => 'Whiplash',
    'genre_ids' => 
    array (
      0 => 18,
      1 => 10402,
    ),
    'original_language' => 'en',
    'original_title' => 'Whiplash',
    'popularity' => 11.036484,
    'id' => 244786,
    'backdrop_path' => '/6bbZ6XyvgfjhQwbplnUh1LSj1ky.jpg',
    'overview' => 'Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.',
    'poster_path' => '/lIv1QinFqz4dlp5U4lQ6HaiskOZ.jpg',
  ),
  'height' => 2100,
  'vote_average' => 6.4240000000000004,
  'width' => 1400,
)
```

**Comment by yukoff** [comment]
Fixed in #148
